# Generated by Django 3.2.8 on 2021-10-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnd', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('gioitinh', models.CharField(max_length=200, null=True)),
                ('namsinh', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
