# Generated by Django 3.2.8 on 2021-10-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webform',
            old_name='cmnd',
            new_name='dongia',
        ),
        migrations.RenameField(
            model_name='webform',
            old_name='gioitinh',
            new_name='dvt',
        ),
        migrations.RenameField(
            model_name='webform',
            old_name='name',
            new_name='soluong',
        ),
        migrations.RenameField(
            model_name='webform',
            old_name='namsinh',
            new_name='tenhang',
        ),
    ]
